#!/bin/bash

set -ex

# format code
if [[ $CI ]]; then
    ./.venv/bin/black --check .
    ./.venv/bin/isort --check-only .
else
    ./.venv/bin/black .
    ./.venv/bin/isort .
fi

./node_modules/.bin/pyright tests typings

# type check code
./.venv/bin/mypy tests typings

# lint
./.venv/bin/flake8 tests typings
